In [1]:
import os

from pathlib import Path
os.chdir(Path.cwd().parent)
print(f"Current directory: {Path.cwd()}")

Current directory: /opt/asaldivar/projects/h_lacustris

In [2]:
import cobra
import polars as pl

from memote.suite.tests.test_biomass import test_biomass_consistency

In [3]:
def fix_biomass_consistency(model, biomass_rxn_id):
    print(f"Testing reaction: {biomass_rxn_id}")
    biomass_rxn = model.reactions.get_by_id(biomass_rxn_id)
    mets_in_biomass = biomass_rxn.metabolites
    try:
        test_biomass_consistency(model, biomass_rxn_id)
    except AssertionError as e:
        print(e)
        mets_info = [(met.id, met.formula_weight, coeff) for met, coeff in mets_in_biomass.items()]
        mets_info_df = pl.DataFrame(
            mets_info,
            orient="row",
            schema=["met_id", "formula_weight", "coeff"]
        )
        new_coeffs = normalize_biomass_rxn(mets_info_df)
        biomass_rxn.subtract_metabolites(mets_in_biomass)
        biomass_rxn.add_metabolites(new_coeffs)
    else:
        print("Reaction is ok")

def normalize_biomass_rxn(mets_info_df):
    molecular_mass = 0
    for row in mets_info_df.iter_rows(named=True):
        molecular_mass += row["formula_weight"] * -row["coeff"]

    new_coeffs = {}
    new_mass = 0
    for row in mets_info_df.iter_rows(named=True):
        coeff = 1000 * row["coeff"] / molecular_mass
        new_mass += row["formula_weight"] * -coeff
        new_coeffs[row["met_id"]] = coeff

    print(f"The current molar mass is {molecular_mass / 1000}  mmol / g[CDW] / h")
    print(f"The new molar mass is {new_mass / 1000}  mmol / g[CDW] / h")

    return new_coeffs

In [4]:
model_dir = Path("models/draft/v0.0.1")
model_file = model_dir / "hlacustris.xml"
model = cobra.io.read_sbml_model(model_file)
model

Set parameter Username
Set parameter LicenseID to value 2744905
Academic license - for non-commercial use only - expires 2026-11-26

In [5]:
sol = model.optimize()
model.summary(solution=sol)

In [6]:
print("These mets don't have formula weight\n")
for met in model.reactions.BIOMASS_hlacus_auto.metabolites:
    if not met.formula:
        print(met)

These mets don't have formula weight

In [7]:
biomass_rxn_id = "BIOMASS_hlacus_auto"
fix_biomass_consistency(model, biomass_rxn_id)

Testing reaction: BIOMASS_hlacus_auto
The component molar mass of the biomass reaction BIOMASS_hlacus_auto
sums up to 8.05015986123145             which is outside of the 1e-03
margin from 1 mmol / g[CDW] / h.
The current molar mass is 8.050159861231442  mmol / g[CDW] / h
The new molar mass is 1.0000000000000053  mmol / g[CDW] / h

In [8]:
sol = model.optimize()
model.summary(solution=sol)

In [9]:
cobra.io.write_sbml_model(model, model_file)